/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BoxInput: typeof import('./src/components/BoxInput.vue')['default']
    CharacterPanel: typeof import('./src/components/CharacterPanel.vue')['default']
    CharacterSheet: typeof import('./src/components/CharacterSheet.vue')['default']
    KDMIcon: typeof import('./src/components/KDMIcon.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Shield: typeof import('./src/components/Shield.vue')['default']
  }
}
